//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20220907_ROBERT_AGUILAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public int Id_evento { get; set; }
        public string nombre_institucion { get; set; }
        public string direccion { get; set; }
        public Nullable<int> cantidad_alumnos { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public string tipo_servicio { get; set; }
        public Nullable<int> valor_servicio { get; set; }
    }
}
